### GET all contacts
GET https://cse341-4-dpkk.onrender.com/contacts

### GET contact by ID
GET https://cse341-4-dpkk.onrender.com/contacts/6a00295f53cff474f62fb400

### POST - Create a new contact
POST https://cse341-4-dpkk.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Gracia",
    "lastName": "Binene",
    "email": "grabinene@gmail.com",
    "phone": "208-208-1901",
    "birthday": "2003-04-20"
}

### PUT - Update a contact
PUT https://cse341-4-dpkk.onrender.com/contacts/6a00295f53cff474f62fb400
Content-Type: application/json

{
    "firstName": "Jenolu",
    "lastName": "Binene",
    "email": "jebinene@gmail.com",
    "phone": "782-208-1901",
    "birthday": "2011-05-08"
}

### DELETE - Delete a contact
DELETE https://cse341-4-dpkk.onrender.com/contacts/6a00294953cff474f62fb3fe